services:
  sms-issuer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-sms-issuer
    environment:
      - STORAGE_TYPE=redis
      - REDIS_SENTINEL_HOST=redis-sentinel
      - REDIS_SENTINEL_PORT=26379
      - REDIS_SENTINEL_USERNAME=sentinel_user
      - REDIS_MASTER_NAME=mymaster
      - REDIS_PASSWORD=password123
    ports:
      - "8080:8080"
    volumes:
      - ./local-secrets/sms-issuer:/secrets
    restart: unless-stopped
    networks:
      - app_network

  irma:
    build:
      # downloading and building, because the prebuilt one may not match our local arch
      context: https://github.com/privacybydesign/irmago.git
      dockerfile: Dockerfile
    container_name: irma-server
    ports:
      - "8088:8088"
    volumes:
      - ./local-secrets/irma-server:/config
    command: server --no-tls --no-auth=false --url=http://localhost:8088 --config=/config/config.json
    restart: unless-stopped
    networks:
      - app_network

  redis-sentinel:
    image: bitnami/redis-sentinel:latest
    container_name: redis-sentinel
    environment:
      - REDIS_MASTER_HOST=redis
      - REDIS_MASTER_SET=mymaster
      - REDIS_SENTINEL_QUORUM=2
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=5000
      - REDIS_FAILOVER_TIMEOUT=10000
      - REDIS_SENTINEL_USER=sentinel_user
      - REDIS_PASSWORD=password123
    ports:
      - "26379:26379"
    networks:
      - app_network
    restart: unless-stopped

networks:
  app_network:
    driver: bridge
