# Workflow to check whether changes to master fulfill all requirements.
name: Status checks

on:
  push:
    branches: [ master ]
  pull_request:
  schedule:
    # Run every monday on 9:00 in the morning (UTC).
    - cron: "0 9 * * 1"
  # Make it possible to trigger the checks manually.
  workflow_dispatch:

jobs:
    build-frontend:
      strategy:
        matrix:
          lang: [ en, nl ]
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4

        - uses: actions/setup-node@v4
          with:
            node-version: '18'
            cache: yarn
            cache-dependency-path: frontend/yarn.lock

        - name: Install dependencies
          working-directory: frontend
          run: yarn --frozen-lockfile

        - name: Build
          working-directory: frontend
          run: ./build.sh ${{ matrix.lang }}

        - uses: actions/upload-artifact@v3
          with:
            name: webapp-${{ matrix.lang }}
            path: webapp/build/

    analyze-go:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-go@v5
        - name: Check fmt
          working-directory: backend
          run:  test -z $(gofmt -l .)

        - name: Install GolangCI-Lint
          run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.63.4

        - name: Run linter
          working-directory: backend
          run: golangci-lint run

    test-go:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-go@v5
        - name: Test
          working-directory: backend
          run: go test ./...

    build-docker-image:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Docker meta
          id: meta
          uses: docker/metadata-action@v5
          with:
            images: ghcr.io/${{ github.repository }}
            tags: |
              type=semver,pattern={{major}}.{{minor}}.{{patch}}
              type=raw,value=edge

        - name: Login to GitHub Container Registry
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Build container
          uses: docker/build-push-action@v5
          with:
            context: .
            push: false
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}

