# Workflow to check whether changes to master fulfill all requirements.
name: Status checks

on:
  push:
    branches: [ main ]
  pull_request:
  schedule:
    # Run every monday on 9:00 in the morning (UTC).
    - cron: "0 9 * * 1"
  # Make it possible to trigger the checks manually.
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
    build-frontend:
      strategy:
        matrix:
          lang: [ en, nl ]
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4

        - uses: actions/setup-node@v4
          with:
            node-version: '18'
            cache: npm
            cache-dependency-path: frontend/package-lock.json

        - name: Install dependencies
          working-directory: frontend
          run: npm ci

        - name: Build
          working-directory: frontend
          run: npm run build

    analyze-go:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-go@v5
        - name: Check fmt
          working-directory: backend
          run:  test -z $(gofmt -l .)

        - name: Install GolangCI-Lint
          run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v2.1.6
  
        - name: Run linter
          working-directory: backend
          run: golangci-lint run --timeout 5m

    test-go:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Docker meta
          id: meta
          uses: docker/metadata-action@v5
          with:
            images: ghcr.io/${{ github.repository }}
            tags: |
              type=semver,pattern={{major}}.{{minor}}.{{patch}}
              type=edge

        - name: Login to GitHub Container Registry
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Build Docker image for testing
          run: docker build -t sms-issuer-tests --file Dockerfile.test .

        - name: Run tests
          run: docker run sms-issuer-tests
        

    build-docker-image:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Check whether this event is the HEAD of main
          continue-on-error: true
          id: is-head-main
          run: git rev-parse HEAD | grep -x ${{ github.sha }}
          shell: bash

        - name: Docker meta
          id: meta
          uses: docker/metadata-action@v5
          with:
            images: ghcr.io/${{ github.repository }}
            tags: |
              type=semver,pattern={{major}}.{{minor}}.{{patch}}
              type=edge,enable=${{ steps.is-head-main.outcome == 'success' }}
              type=ref,event=branch,enable=${{ github.event_name == 'workflow_dispatch' }}

        - name: Login to GitHub Container Registry
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Build container
          uses: docker/build-push-action@v5
          with:
            context: .
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}

